[versions]
activity = "1.9.3"
agp = "8.6.1"
androidVersion = "11.7.1"
appcompat = "1.7.0"
calendarview = "v1.0.6"
carUiLib = "2.6.0"
circleimageview = "3.1.0"
constraintlayout = "2.2.0"
converterGson = "2.11.0"
espresso = "3.6.1"
extjunit = "1.2.1"
fragment = "1.8.5"
gradle = "8.6.1"
junit = "4.13.2"
lifecycleProcess = "2.8.7"
material = "1.12.0"
navigationFragment = "2.8.3"
navigationUi = "2.8.3"
okhttp = "4.12.0"
playServicesBase = "18.5.0"
retrofit = "2.11.0"
shimmer = "0.5.0"
swiperefreshlayout = "1.2.0-alpha01"
legacySupportV4 = "1.0.0"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"
playServicesMaps = "19.0.0"
playServicesAds = "23.5.0"

[libraries]
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
calendarview = { module = "com.github.hdev0225:CalendarView", version.ref = "calendarview" }
car-ui-lib = { group = "com.android.car.ui", name = "car-ui-lib", version.ref = "carUiLib" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "extjunit" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleProcess" }
maps-android = { module = "com.mapbox.maps:android", version.ref = "androidVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationFragment" }
navigation-dynamic-features-fragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigationFragment" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
play-services-base = { group = "com.google.android.gms", name = "play-services-base", version.ref = "playServicesBase" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "playServicesAds" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }