[versions]
activity = "1.9.1"
agp = "8.6.0"
appcompat = "1.7.0"
calendarview = "v1.0.6"
circleimageview = "3.1.0"
constraintlayout = "2.1.4"
espresso = "3.6.1"
extjunit = "1.2.1"
gradle = "8.6.0"
junit = "4.13.2"
material = "1.12.0"
okhttp = "4.9.1"
playServicesBase = "18.5.0"
shimmer = "0.5.0"
swiperefreshlayout = "1.2.0-alpha01"

[libraries]
calendarview = { module = "com.github.hdev0225:CalendarView", version.ref = "calendarview" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "extjunit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
play-services-base = { group = "com.google.android.gms", name = "play-services-base", version.ref = "playServicesBase" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

